# Generated by Django 4.1.1 on 2022-09-21 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0003_pronostic_info_pronostic_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
