# Generated by Django 4.1.1 on 2022-09-22 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0004_pronostic_user_tournament_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='users',
        ),
        migrations.CreateModel(
            name='TournamentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_prize', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='tournaments_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
