# Generated by Django 4.1.1 on 2022-09-22 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0005_remove_tournament_users_tournamentroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentroom',
            name='users',
            field=models.ManyToManyField(related_name='tournaments_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
