# Generated by Django 4.1.1 on 2022-09-22 00:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0006_alter_tournamentroom_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentRoom',
            new_name='Room',
        ),
    ]
