# Generated by Django 4.1.1 on 2022-09-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostic',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.room'),
            preserve_default=False,
        ),
    ]
