# Generated by Django 4.1.1 on 2022-09-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_pronostic_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_knockout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='penalties_win',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pronostic',
            name='penalties_win',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
