# Generated by Django 4.1.1 on 2022-11-01 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_game_is_knockout_game_penalties_win_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 21, 11, 28, 392799)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pronostic",
            name="last_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 21, 11, 22, 937109)
            ),
        ),
    ]
