# Generated by Django 4.1.1 on 2022-11-03 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0013_alter_pronostic_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pronostic",
            name="last_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 3, 15, 8, 30, 457181)
            ),
        ),
        migrations.AlterField(
            model_name="pronostic",
            name="penalties_win",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "------------"), (1, "Home Team"), (2, "Away Team")],
                default=0,
            ),
        ),
    ]
