# Generated by Django 4.1.1 on 2022-11-03 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0015_alter_pronostic_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_code",
            field=models.CharField(blank=True, default="32XYKECI", max_length=8),
        ),
        migrations.AlterField(
            model_name="pronostic",
            name="last_modified",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 3, 17, 23, 33, 497501)
            ),
        ),
    ]
