# Generated by Django 4.1.1 on 2022-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0018_team_fifa_code_alter_pronostic_last_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="fifa_code",
            field=models.CharField(max_length=3),
        ),
    ]
