# Generated by Django 4.1.1 on 2022-11-15 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0019_alter_team_fifa_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pronostic",
            name="last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
