# Generated by Django 4.1.1 on 2022-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0020_alter_pronostic_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="played",
            field=models.BooleanField(default=False),
        ),
    ]
