# Generated by Django 4.1.1 on 2024-05-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0022_game_game_instance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pronostic",
            name="room",
        ),
    ]
