version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/usr/src/prode_qatar_2022/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    entrypoint: sh /usr/src/prode_qatar_2022/docker-entrypoint.sh
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    ports:
      - "5432:5432"

volumes:
  postgres_data: